name: mawaqit
description: Connecting Muslims to Mosques

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.2-tv+173

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # FIREBASE PACKAGES
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  firebase_analytics: ^9.1.7
  firebase_crashlytics: ^2.7.2

  # STORAGE
  shared_preferences: ^2.0.13

  # UI
  cupertino_icons: ^1.0.4
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.5
  #modal_progress_hud: ^0.1.3
  flutter_inappwebview: ^5.4.3+7

  # CONNECTIVITY
  http: ^0.13.4
  dio: ^4.0.6

  share: ^2.0.4
  launch_review: ^3.0.1
  url_launcher: ^6.1.0
  store_redirect: ^2.0.1
  connectivity: ^3.0.6
  uni_links: ^0.5.1

  # TOOLS
  google_fonts: ^2.3.2
  package_info: ^2.0.2
  android_intent: ^2.0.2
  global_configuration: ^2.0.0-nullsafety.1
  wakelock: ^0.6.2
  #flutter_downloader: 1.6.1
  #  flutter_barcode_scanner: ^2.0.0
  flutter_speed_dial: ^6.0.0

  # STATE MANAGEMENT
  provider: ^6.0.2
  flutter_riverpod: ^1.0.4
  path_provider: ^2.0.9

  animated_text_kit: ^4.2.2
  marquee: ^2.2.3
  text_scroll: ^0.1.0

  easy_debounce: ^2.0.2+1

  # MAP
  #location: ^4.3.0
  geolocator: ^8.2.1
  hijri: ^3.0.0
#  webview_flutter: ^3.0.0

  rive_splash_screen: ^0.1.0
  lottie: ^1.3.0
  flutter_svg: ^1.0.3
  introduction_screen: ^3.0.2
  dots_indicator: ^2.1.0
  sizer: ^2.0.15

  timeago_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/img/
    - assets/img/flag/
    - assets/cfg/
    - assets/scripts/
    - assets/backgrounds/
    - assets/animations/rive/
    - assets/animations/lottie/
    - assets/img/logo/
    - assets/icon/


  fonts:
    - family: MawaqitIcons
      fonts:
        - asset: assets/fonts/MawaqitIcons.ttf

flutter_intl:
  enabled: true
