name: mawaqit
description: Connecting Muslims to Mosques

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


version: 1.18.3+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # FIREBASE PACKAGES
  firebase_core: ^2.11.0
  firebase_analytics: ^10.3.0
  firebase_crashlytics: ^3.2.0

  # monitoring/logging
  sentry_flutter: ^7.5.2
  logger: ^2.0.2+1

  # STORAGE
  shared_preferences: ^2.1.1
  hive_flutter: ^1.1.0

  # UI
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  flutter_spinkit: ^5.2.0
  page_transition: ^2.0.9
  fluttertoast: ^8.0.8
  #modal_progress_hud: ^0.1.3
  flutter_inappwebview: ^5.7.2+3

  # CONNECTIVITY
  http: ^0.13.6
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  cached_network_image: ^3.2.3
  xml_parser: ^1.0.0

  share_plus: ^6.3.1
  launch_review: ^3.0.1
  url_launcher: ^6.1.11
  store_redirect: ^2.0.1
  connectivity_plus: ^4.0.0
  uni_links: ^0.5.1

  # TOOLS
  google_fonts: ^4.0.4
  device_info_plus: ^9.0.2
  android_intent_plus: ^4.0.0
  global_configuration: ^2.0.0-nullsafety.1
  path_provider: ^2.0.14
  uuid: ^3.0.5

  # STATE MANAGEMENT
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6
  wifi_hunter: ^1.1.1+2
  flutter_styled_toast: ^2.2.1
  flutter_keyboard_visibility: ^6.0.0
  auto_size_text: ^3.0.0
  flutter_animate: ^4.1.1+1
  marquee: ^2.2.3
  text_scroll: ^0.2.0

  easy_debounce: ^2.0.3

  # MAP
  #location: ^4.3.0
  geolocator: ^9.0.2
  hijri: ^3.0.0

  #  webview_flutter: ^3.0.0
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  rive_splash_screen: ^0.1.1
  lottie: ^2.3.2
  flutter_svg: ^2.0.5
  dots_indicator: ^3.0.0
  sizer: ^2.0.15

  timeago_flutter: ^3.4.0
  timezone:
  wifi_scan: ^0.4.1

  #  media
  youtube_player_flutter: ^8.1.2
  youtube_explode_dart: ^1.12.4
  unique_identifier: ^0.3.0
  collection: any
  disk_space: ^0.2.1

  equatable: ^2.0.5
  just_audio: ^0.9.37


  # alert
  flash: ^3.0.5+2

  # app update
  upgrader: ^6.5.0
  open_store: ^0.5.0

  # internet connectivity checker
  internet_connection_checker_plus: ^1.0.1
  flutter_kurdish_localization: ^1.0.8
  scrollview_observer: ^1.21.0
  # manage files and folders
  flutter_archive: ^6.0.3

  shimmer: ^3.0.0

  wakelock_plus: 1.1.4
  wakelock_plus_platform_interface: 1.1.0
  percent_indicator: ^4.2.3

  # functional programming
  fpdart: ^1.1.0

  # automatic scrolling
  scroll_to_index: ^3.0.1
  fast_cached_network_image: ^1.2.0

  montenegrin_localization: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # to get unused packages run
  # flutter pub run dependency_validator
  dependency_validator:
  build_runner: ^2.4.9
  http_mock_adapter: ^0.6.1
  flutter_background_service: ^2.1.3
  flutter_lints: 3.0.1
  hive_generator: ^2.0.1
  mocktail: ^1.0.3
  dart_mappable_builder: ^4.2.3
  json_serializable: ^6.8.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

dependency_overrides:
  win32: 5.0.5
  rive: ^0.9.1
# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/img/
    - assets/img/flag/
    - assets/cfg/
    - assets/scripts/
    - assets/backgrounds/
    - assets/animations/rive/
    - assets/animations/lottie/
    - assets/svg/
    - assets/voices/
    - assets/voices/adhan/
    - assets/img/quran/
    - assets/icon/

  fonts:
    - family: MawaqitIcons
      fonts:
        - asset: assets/fonts/MawaqitIcons.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/original-hafs.ttf
    - family: kufi
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
    - family: arial
      fonts:
        - asset: assets/fonts/ARIAL.TTF
    - family: helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/weathericons-regular-webfont.ttf
